name: Update Requirements

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  update-requirements:
    runs-on: ubuntu-latest

    env:
      PR_MERGED: true
      ORIGIN_BRANCH: ${{ github.event.pull_request.head.ref }}
      TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}
      
    steps:
    - name: Check if PR was merged
      run: echo "PR_MERGED=$(jq -r '.pull_request.merged' "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Run update script
      run: python update_requirements.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add requirements.txt
        git commit -m "Update the pointed branch of our internal dependencies after PR merge"
        git push

      if: env.PR_MERGED == 'true'
